export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_ALL_POKEMONS_STARTED = 'GET_ALL_POKEMONS_STARTED';
export const GET_ALL_POKEMONS_SUCCESS = 'GET_ALL_POKEMONS_SUCCESS';
export const GET_ALL_POKEMONS_FAILED = 'GET_ALL_POKEMONS_FAILED';

export const GET_POKEMON_DETAILS = 'GET_POKEMON_DETAILS';
export const GET_POKEMON_DETAILS_STARTED = 'GET_POKEMON_DETAILS_STARTED';
export const GET_POKEMON_DETAILS_SUCCESS = 'GET_POKEMON_DETAILS_SUCCESS';
export const GET_POKEMON_DETAILS_FAILED = 'GET_POKEMON_DETAILS_FAILED';